package telegram.bot.video.security.entity;
// Generated May 15, 2018 4:15:47 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * CaptureReport generated by hbm2java
 */
@Entity
@Table(name = "capture_report", catalog = "telegrambotvideosecurity",
        uniqueConstraints = {@UniqueConstraint(columnNames = "report_name"), @UniqueConstraint(columnNames = "capture_id")}
)
public class CaptureReport extends IEntity {

    private Capture capture;
    private byte[] report;
    private String reportName;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "capture_id", unique = true, nullable = false)
    public Capture getCapture() {
        return this.capture;
    }

    public void setCapture(Capture capture) {
        this.capture = capture;
    }

    @Column(name = "report", nullable = false)
    public byte[] getReport() {
        return this.report;
    }

    public void setReport(byte[] report) {
        this.report = report;
    }

    @Column(name = "report_name", unique = true, nullable = false)
    public String getReportName() {
        return this.reportName;
    }

    public void setReportName(String reportName) {
        this.reportName = reportName;
    }
}


