package telegram.bot.video.security.entity;
// Generated May 11, 2018 7:26:25 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Capture generated by hbm2java
 */
@Entity
@Table(name = "capture", catalog = "telegrambotvideosecurity")
public class Capture extends IEntity {

    private String camName;
    private Date dateStarted;
    private Date dateFinished;
    private int sensivity;
    private String uid;
    private int pollInterval;
    private String minorName;
    private String mediumName;
    private String majorName;
    private Set<CaptureStatistics> stats = new HashSet<>(0);

    @Column(name = "cam_name", nullable = false)
    public String getCamName() {
        return this.camName;
    }

    public void setCamName(String camName) {
        this.camName = camName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_started", nullable = false, length = 19)
    public Date getDateStarted() {
        return this.dateStarted;
    }

    public void setDateStarted(Date dateStarted) {
        this.dateStarted = dateStarted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_finished", length = 19)
    public Date getDateFinished() {
        return this.dateFinished;
    }

    public void setDateFinished(Date dateFinished) {
        this.dateFinished = dateFinished;
    }

    @Column(name = "sensivity", nullable = false)
    public int getSensivity() {
        return this.sensivity;
    }

    public void setSensivity(int sensivity) {
        this.sensivity = sensivity;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "capture")
    public Set<CaptureStatistics> getStats() {
        return this.stats;
    }

    public void setStats(Set<CaptureStatistics> stats) {
        this.stats = stats;
    }

    @Column(name = "uid", nullable = false, length = 45)
    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    @Column(name = "poll_interval", nullable = false)
    public int getPollInterval() {
        return this.pollInterval;
    }

    public void setPollInterval(int pollInterval) {
        this.pollInterval = pollInterval;
    }

    @Column(name = "minor_name", nullable = false, length = 45)
    public String getMinorName() {
        return this.minorName;
    }

    public void setMinorName(String minorName) {
        this.minorName = minorName;
    }

    @Column(name = "medium_name", nullable = false, length = 45)
    public String getMediumName() {
        return this.mediumName;
    }

    public void setMediumName(String mediumName) {
        this.mediumName = mediumName;
    }

    @Column(name = "major_name", nullable = false, length = 45)
    public String getMajorName() {
        return this.majorName;
    }

    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }
}


