package telegram.bot.video.security.entity;
// Generated Nov 19, 2018 1:05:34 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Face generated by hbm2java
 */
@Entity
@Table(name = "face", catalog = "telegrambotvideosecurity")
public class Face extends IEntity {

    private Person person;
    private byte[] face;

    public Face() {
    }

    public Face(Person p, byte[] face) {
        this.person = p;
        this.face = face;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "person_id", nullable = false)
    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    @Lob
    @Column(name = "face", nullable = false)
    public byte[] getFace() {
        return this.face;
    }

    public void setFace(byte[] face) {
        this.face = face;
    }
}