package telegram.bot.video.security.entity;
// Generated Nov 19, 2018 1:05:34 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "telegrambotvideosecurity")
public class Person extends IEntity {

    private String firstName;
    private String lastName;
    private Set<Face> faces = new HashSet<>(0);

    public Person() {
    }

    public Person(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    @Column(name = "first_name", nullable = false, length = 45)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", nullable = false, length = 45)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "person")
    public Set<Face> getFaces() {
        return this.faces;
    }

    public void setFaces(Set<Face> faces) {
        this.faces = faces;
    }
}


